### ISSUE TITLE
please add a way to accept self signed certificate 

### ISSUE THREAD

**Issue by jithinjames916** [Materialious/Materialious#347] opened 2024-06-07 16:31 UTC
I am hosting my on instance with self signed cert. I installed the cert on the mobile, On browser the cert is accepted but in the app is shows
Oh no! You've encountered an error.
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

If it's my fault please reply a solution or add it if you can

**Comment by WardPearce** [comment] 2024-06-07 16:33
Duplicate of #337

**Closed by WardPearce** 2024-06-07 16:33 UTC
