### ISSUE TITLE
Dash videos not autoplaying

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [Materialious/Materialious#401] opened 2024-07-11 13:32 UTC
**Describe the bug**
Videos via dash don't autoplay, and "auto" quality basically perma sets itself to 144p. Even if it remembers I want 1080p, upon manually clicking start it sets itself to low quality.

**To Reproduce**
1. Enable dash
2. Go to a video
3. See in your console it shows a warning
4. Manually click start

**Expected behavior**
Video autoplays with a good auto quality, it easily runs in max quality if i manually set it after starting the video.

**Screenshots**
![Screenshot_20240711_143118](https://github.com/Materialious/Materialious/assets/8694395/6ca7ca19-df5c-4a0c-8540-b94e1532f097)

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Browser Floorp
 - Version 11.15.0

**Additional context**

**Comment by WardPearce** [comment] 2024-07-11 13:35
Quality issue is a duplicate of #41
Autoplay for dash is handled via Vidstack, so issue should be raised there.

**Closed by WardPearce** 2024-07-11 13:35 UTC
